server:
  port: 8080

spring:
  application:
    name: order

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    schemas: orders

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: orders

clients:
  product:
    url: ${PRODUCT_SERVICE_URL:http://product-service:8080}

management:
  endpoints:
    web:
      base-path: /orders/actuator
      exposure:
        include: ['prometheus']

logging:
  level:
    root: info
    store: debug
